name: microbe_seg_ve
channels:
  - pytorch
  - conda-forge
  - anaconda
  - nvidia
  - ome
dependencies:
  - cudnn=8.2.1
  - cudatoolkit=11.3
  - imageio=2.13.3
  - imgaug=0.4.0
  - ipython=7.30.1
  - matplotlib=3.5.1
  - numpy=1.21.4
  - omero-py=5.10.2
  - opencv=4.5.3
  - pandas=1.3.5
  - pillow=8.4.0
  - pyqt=5.12.3
  - python=3.8.12
  - pytorch=1.10
  - qimage2ndarray=1.8.3
  - qt=5.12.9
  - scikit-image=0.19.0
  - scipy=1.7.3
  - tifffile=2021.11.2
  - torchvision=0.11.1
  - pip=21.3.1
  - pip:
    - imagecodecs==2021.11.20
    - slidingwindow==0.0.14